### Check for user account creation
POST http://localhost:8000/user/create-account
Content-Type: application/json

{
    "email": "pratik18Mar@gmail.com",
    "password": "pratik2408s",
    "firstName": "Pratik",
    "lastName": "Sharma"
}


### Check for login user p@gmail.com
POST http://localhost:8000/user/login
Content-Type: application/json

{
    "email": "pratik18Mar@gmail.com",
    "password": "pratik2408s"
}

### Create the expense
POST http://localhost:8000/expense/create-expense
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY3ZDkyNWY4MTM1MDA3NjRhY2UwMTY0OCIsImZpcnN0TmFtZSI6IlByYXRpayIsImxhc3ROYW1lIjoiU2hhcm1hIiwiZW1haWwiOiJwcmF0aWsxOE1hckBnbWFpbC5jb20iLCJjcmVhdGVkT24iOiIyMDI1LTAzLTE4VDA3OjUxOjIwLjQ0OVoiLCJfX3YiOjB9LCJpYXQiOjE3NDIyODc4OTgsImV4cCI6MTc0MjI5MTQ5OH0.n9P8h7XIrulUT424ihD7GnOpYuJjt8XrNeMVl3iSXSM

{
    "title": "Traveling",
    "amount": 100,
    "description": "stay in picnic",
    "category": "Food",
    "date": "2024-08-19",
    "type": "debit"
}

### Get expense by user
GET http://localhost:8000/expense?page=1&limit=2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY3ZDkyNWY4MTM1MDA3NjRhY2UwMTY0OCIsImZpcnN0TmFtZSI6IlByYXRpayIsImxhc3ROYW1lIjoiU2hhcm1hIiwiZW1haWwiOiJwcmF0aWsxOE1hckBnbWFpbC5jb20iLCJjcmVhdGVkT24iOiIyMDI1LTAzLTE4VDA3OjUxOjIwLjQ0OVoiLCJfX3YiOjB9LCJpYXQiOjE3NDIyODc4OTgsImV4cCI6MTc0MjI5MTQ5OH0.n9P8h7XIrulUT424ihD7GnOpYuJjt8XrNeMVl3iSXSM


### Get summary of expense
GET http://localhost:8000/expense/getSummary?type=weekly
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY3ZDkyNWY4MTM1MDA3NjRhY2UwMTY0OCIsImZpcnN0TmFtZSI6IlByYXRpayIsImxhc3ROYW1lIjoiU2hhcm1hIiwiZW1haWwiOiJwcmF0aWsxOE1hckBnbWFpbC5jb20iLCJjcmVhdGVkT24iOiIyMDI1LTAzLTE4VDA3OjUxOjIwLjQ0OVoiLCJfX3YiOjB9LCJpYXQiOjE3NDIyODc4OTgsImV4cCI6MTc0MjI5MTQ5OH0.n9P8h7XIrulUT424ihD7GnOpYuJjt8XrNeMVl3iSXSM


### Search expense by date, query
GET http://localhost:8000/expense?date=2024-08-19
Content-Type: application/json
Authorization: Bearer Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY3ZDkyNWY4MTM1MDA3NjRhY2UwMTY0OCIsImZpcnN0TmFtZSI6IlByYXRpayIsImxhc3ROYW1lIjoiU2hhcm1hIiwiZW1haWwiOiJwcmF0aWsxOE1hckBnbWFpbC5jb20iLCJjcmVhdGVkT24iOiIyMDI1LTAzLTE4VDA3OjUxOjIwLjQ0OVoiLCJfX3YiOjB9LCJpYXQiOjE3NDIyODc4OTgsImV4cCI6MTc0MjI5MTQ5OH0.n9P8h7XIrulUT424ihD7GnOpYuJjt8XrNeMVl3iSXSM


### Get the expense by id
GET http://localhost:8000/expense/67d9398919be1574a81d106e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY3ZDkyNWY4MTM1MDA3NjRhY2UwMTY0OCIsImZpcnN0TmFtZSI6IlByYXRpayIsImxhc3ROYW1lIjoiU2hhcm1hIiwiZW1haWwiOiJwcmF0aWsxOE1hckBnbWFpbC5jb20iLCJjcmVhdGVkT24iOiIyMDI1LTAzLTE4VDA3OjUxOjIwLjQ0OVoiLCJfX3YiOjB9LCJpYXQiOjE3NDIyODc4OTgsImV4cCI6MTc0MjI5MTQ5OH0.n9P8h7XIrulUT424ihD7GnOpYuJjt8XrNeMVl3iSXSM


### Delete the expense by id
DELETE http://localhost:8000/expense/67d9398919be1574a81d106e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY3ZDkyNWY4MTM1MDA3NjRhY2UwMTY0OCIsImZpcnN0TmFtZSI6IlByYXRpayIsImxhc3ROYW1lIjoiU2hhcm1hIiwiZW1haWwiOiJwcmF0aWsxOE1hckBnbWFpbC5jb20iLCJjcmVhdGVkT24iOiIyMDI1LTAzLTE4VDA3OjUxOjIwLjQ0OVoiLCJfX3YiOjB9LCJpYXQiOjE3NDIyODc4OTgsImV4cCI6MTc0MjI5MTQ5OH0.n9P8h7XIrulUT424ihD7GnOpYuJjt8XrNeMVl3iSXSM


### Update the expense by id
PUT http://localhost:8000/expense/67d9398919be1574a81d106e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY3ZDkyNWY4MTM1MDA3NjRhY2UwMTY0OCIsImZpcnN0TmFtZSI6IlByYXRpayIsImxhc3ROYW1lIjoiU2hhcm1hIiwiZW1haWwiOiJwcmF0aWsxOE1hckBnbWFpbC5jb20iLCJjcmVhdGVkT24iOiIyMDI1LTAzLTE4VDA3OjUxOjIwLjQ0OVoiLCJfX3YiOjB9LCJpYXQiOjE3NDIyODc4OTgsImV4cCI6MTc0MjI5MTQ5OH0.n9P8h7XIrulUT424ihD7GnOpYuJjt8XrNeMVl3iSXSM

{
    "title": "TravelingToHostel",
    "amount": 100,
    "description": "stay in picnicssss",
    "category": "Food",
    "date": "2024-08-19",
    "type": "debit"
}