const DELETE_EXPENSE_CHANNEL = 'DELETE_EXPENSE'
const UPDATE_EXPENSE_CHANNEL = 'UPDATE_EXPENSE'
const CREATE_EXPENSE_CHANNEL = 'CREATE_EXPENSE'

module.exports = {
    DELETE_EXPENSE_CHANNEL,
    UPDATE_EXPENSE_CHANNEL,
    CREATE_EXPENSE_CHANNEL
}